# Generated by Django 5.2.17 on 2026-09-21 04:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reorder_level', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.manufacturer')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medicines_m_name_61a774_idx'), models.Index(fields=['generic_name'], name='medicines_m_generic_1e9386_idx'), models.Index(fields=['barcode'], name='medicines_m_barcode_ac4d36_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'strength', 'dosage_form', 'manufacturer'), name='unique_medicine_combination')],
            },
        ),
    ]
