# Generated by Django 5.2.17 on 2026-09-21 04:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='medicines.medicine')),
            ],
            options={
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['medicine', 'expiry_date'], name='inventory_b_medicin_647aed_idx'), models.Index(fields=['expiry_date'], name='inventory_b_expiry__96c551_idx'), models.Index(fields=['batch_number'], name='inventory_b_batch_n_6c5580_idx')],
                'constraints': [models.UniqueConstraint(fields=('medicine', 'batch_number'), name='unique_medicine_batch')],
            },
        ),
    ]
